# 04b - Multiclass Federated Learning with Edge IIoT Dataset using Flower and TensorFlow/Keras

In this notebook we use the Flower Federated Learning library (flower.dev) with Tensorflow/Keras to distribute the Edge-IIoT data across multiple clients in various different ways.

In [1]:
### THIS SECTION NEEDS TO BE SET TO DETERMINE WHICH CONFIGURATION METHOD TO UTILISE

SPLIT_AVAILABLE_METHODS = ['INDIVIDUAL_ATTACK', 'ATTACK_GROUP', 'STRATIFIED']
METHOD = 'STRATIFIED'
NUM_OF_STRATIFIED_CLIENTS = 10 # only applies to stratified method
print (METHOD)

STRATIFIED


In [2]:
%%capture
%pip install flwr[simulation] torch torchvision matplotlib sklearn openml

In [3]:
import os
import pandas as pd
import numpy as np
import flwr as fl
import sklearn
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torchvision
import torch.nn.functional as F
import torchvision.transforms as transforms
from flwr.common import Metrics
from torch.utils.data import DataLoader, random_split
from torchvision.datasets import CIFAR10


In [4]:
print("flwr", fl.__version__)
print("numpy", np.__version__)
print("torch", torch.__version__)
print("torchvision", torchvision.__version__)

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Training on {DEVICE}")

flwr 1.3.0
numpy 1.24.2
torch 1.13.1
torchvision 0.14.1
Training on cuda:0


In [5]:
dataset_path = "../datasets/Edge-IIoT/"

df = pd.read_pickle(dataset_path + "Edge-IIoTset dataset/Selected dataset for ML and DL/ML-EdgeIIoT-dataset.pkl")   

## Make dataframe for Multi-class classification

In [6]:
# Multiclass attack dataframe
multiclass_df = df[['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4',
       'arp.opcode', 'arp.hw.size', 'arp.src.proto_ipv4', 'icmp.checksum',
       'icmp.seq_le', 'icmp.transmit_timestamp', 'icmp.unused',
       'http.file_data', 'http.content_length', 'http.request.uri.query',
       'http.request.method', 'http.referer', 'http.request.full_uri',
       'http.request.version', 'http.response', 'http.tls_port', 'tcp.ack',
       'tcp.ack_raw', 'tcp.checksum', 'tcp.connection.fin',
       'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack',
       'tcp.dstport', 'tcp.flags', 'tcp.flags.ack', 'tcp.len', 'tcp.options',
       'tcp.payload', 'tcp.seq', 'tcp.srcport', 'udp.port', 'udp.stream',
       'udp.time_delta', 'dns.qry.name', 'dns.qry.name.len', 'dns.qry.qu',
       'dns.qry.type', 'dns.retransmission', 'dns.retransmit_request',
       'dns.retransmit_request_in', 'mqtt.conack.flags',
       'mqtt.conflag.cleansess', 'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len',
       'mqtt.msg_decoded_as', 'mqtt.msg', 'mqtt.msgtype', 'mqtt.proto_len',
       'mqtt.protoname', 'mqtt.topic', 'mqtt.topic_len', 'mqtt.ver',
       'mbtcp.len', 'mbtcp.trans_id', 'mbtcp.unit_id',
       'Attack_type']]

In [7]:
known_sensor_ip_addresses = [ '192.168.0.101', '192.168.2.194', '192.168.3.18', '192.168.4.73', '192.168.5.47', '192.168.6.56', '192.768.7.62', '192.168.8.163']
print ("known_sensor_ip_addresses:", known_sensor_ip_addresses)

tcp_dos_attack_ip_addresses = [ '207.192.25.133', '94.196.109.185', '133.149.252.77', '220.146.94.148' ]
tdp_dos_atack_ip_addresses = [ '190.123.219.128', '16.226.184.201', '153.125.214.15', '91.184.12.91' ]
http_attack_ip_addresses = [ '192.168.0.170', '216.58.198.74' ]
icmp_flood_attack_ip_addresses = [ '213.117.18.213', '183.223.100.122', '166.153.227.121', '49.81.59.152', '227.117.33.125' ]
port_scan_attack_ip_addresses = [ '192.168.0.170' ]
os_fingerprinting_attack_ip_addresses = [ '192.168.0.170' ]
vuln_scan_attack_ip_addresses = [ '192.168.0.170', '142.250.200.205', '172.217.19.35', '142.250.201.10' ]
dns_spoof_attack_ip_addresses = [ '192.168.0.101', '192.168.0.152', '172.217.19.35', '192.168.0.170' ]
arp_spoof_attack_ip_addresses = [ '192.168.0.101', '192.168.0.152', '172.217.19.35', '192.168.0.170' ]
xss_attack_ip_addresses = [ '192.168.0.170', '172.217.19.42', '104.16.87.20' ]
sql_injection_attack_ip_addresses = [ '192.168.0.170' ]
upload_attack_ip_addresses = [ '192.168.0.170' ]
backdoor_attack_ip_addresses = [ '192.168.0.170' ]
password_attack_ip_addresses = [ '192.168.0.170' ]
ransomware_attack_ip_addresses = [ '192.168.0.170' ] 

# Combine all attack IP addresses into one list, ensuring no duplicates
known_attacker_ip_addresses = list(set(tcp_dos_attack_ip_addresses + tdp_dos_atack_ip_addresses + http_attack_ip_addresses + icmp_flood_attack_ip_addresses + port_scan_attack_ip_addresses + os_fingerprinting_attack_ip_addresses + vuln_scan_attack_ip_addresses + dns_spoof_attack_ip_addresses + arp_spoof_attack_ip_addresses + xss_attack_ip_addresses + sql_injection_attack_ip_addresses + upload_attack_ip_addresses + backdoor_attack_ip_addresses + password_attack_ip_addresses + ransomware_attack_ip_addresses))
print (f"known_attacker_ip_addresses: \nNumber of IPs {len(known_attacker_ip_addresses)}\n{known_attacker_ip_addresses}")


known_sensor_ip_addresses: ['192.168.0.101', '192.168.2.194', '192.168.3.18', '192.168.4.73', '192.168.5.47', '192.168.6.56', '192.768.7.62', '192.168.8.163']
known_attacker_ip_addresses: 
Number of IPs 22
['207.192.25.133', '153.125.214.15', '192.168.0.152', '142.250.201.10', '220.146.94.148', '91.184.12.91', '192.168.0.101', '183.223.100.122', '94.196.109.185', '166.153.227.121', '133.149.252.77', '172.217.19.35', '104.16.87.20', '142.250.200.205', '172.217.19.42', '190.123.219.128', '227.117.33.125', '216.58.198.74', '213.117.18.213', '192.168.0.170', '16.226.184.201', '49.81.59.152']


With the exception of DDOS attacks, the attacks mainly come from a small subset of IP addresses. `192.168.0.170` being responsible for a lot of the attacks. From the data exploration workbook `02b-ML-Data-Exploration.ipynb` we can also see that the attacked IP is always the `192.168.0.128` edge server. This means it is not feasible the divide the traffic either by attacker or attacked IP address.

## Multiclass Classification

Categorical data encoding (Dummy Encoding):

EG. Takes a product category and converts it to a binary vector

In [8]:
def encode_text_dummy(df, name):

    dummies = pd.get_dummies(df[name])

    for x in dummies.columns:

        dummy_name = f"{name}-{x}"

        df[dummy_name] = dummies[x]

    df.drop(name, axis=1, inplace=True)

encode_text_dummy(multiclass_df,'http.request.method')

encode_text_dummy(multiclass_df,'http.referer')

encode_text_dummy(multiclass_df,"http.request.version")

encode_text_dummy(multiclass_df,"dns.qry.name.len")

encode_text_dummy(multiclass_df,"mqtt.conack.flags")

encode_text_dummy(multiclass_df,"mqtt.protoname")

encode_text_dummy(multiclass_df,"mqtt.topic")

In [9]:
# print max index value of binary_df
print("max index value of binary_df:", max(multiclass_df.index))
print(multiclass_df.shape)

max index value of binary_df: 157799
(157800, 90)


We need to drop some unrequired columns from the DF, but we need to keep the original around as we may need to split the data differently for different models based on things like the IP address

In [10]:
#drop_columns = ["frame.time", "ip.src_host", "ip.dst_host", "arp.src.proto_ipv4","arp.dst.proto_ipv4", 
drop_columns = ["frame.time", "arp.src.proto_ipv4","arp.dst.proto_ipv4", 

         "http.file_data","http.request.full_uri","icmp.transmit_timestamp",

         "http.request.uri.query", "tcp.options","tcp.payload","tcp.srcport",

         "tcp.dstport", "udp.port", "mqtt.msg"]

multiclass_df = multiclass_df.drop(drop_columns, axis=1)

multiclass_df = multiclass_df.dropna(axis=0, how='any')

multiclass_df = multiclass_df.drop_duplicates(subset=None, keep="first")

# We cant shuffle at this point as we need to keep the order so we can split the dataset later based on things like IP address
#binary_df_copy = shuffle(binary_df_copy)

# Compute the number of missing values (NaN or null) in each column of a pandas DataFrame object named df.
multiclass_df.isna().sum()

ip.src_host                            0
ip.dst_host                            0
arp.opcode                             0
arp.hw.size                            0
icmp.checksum                          0
                                      ..
mqtt.protoname-0.0                     0
mqtt.protoname-MQTT                    0
mqtt.topic-0                           0
mqtt.topic-0.0                         0
mqtt.topic-Temperature_and_Humidity    0
Length: 77, dtype: int64

In [11]:
# print max index value of binary_df
print("max index value of binary_df:", max(multiclass_df.index))
print(multiclass_df.shape)

multiclass_df.reset_index(drop=True, inplace=True)

# print max index value of binary_df
print("max index value of binary_df:", max(multiclass_df.index))
print(multiclass_df.shape)


max index value of binary_df: 157799
(153225, 77)
max index value of binary_df: 153224
(153225, 77)


Change the Attack Type to be a unique number for the attack type

In [12]:
# Creating a dictionary of Types
attacks = {'Normal': 0 ,'Backdoor' :1, 'DDoS_HTTP':2,  'DDoS_ICMP':3, 'DDoS_TCP':4, 'DDoS_UDP':5, 
           'Fingerprinting':6, 'MITM':7, 'Password':8, 'Port_Scanning':9, 'Ransomware':10, 
           'SQL_injection':11, 'Uploading':12, 'Vulnerability_scanner':13, 'XSS':14}

multiclass_df['Attack_type'] = multiclass_df['Attack_type'].map(attacks)


In [13]:
label = multiclass_df['Attack_type']
le = preprocessing.LabelEncoder()
label_n = le.fit_transform(label.values)

# Stratify based on the attack label to balance the dataset - This is our original copy of the data include IP addresses
X_train_df, X_test_df, y_train_df, y_test_df = train_test_split(multiclass_df, label_n, stratify=label_n, test_size=0.2, random_state=42)

print(X_train_df.shape)

X_train_df.reset_index(drop=True, inplace=True)

#print the max index of X_train_df
print(X_train_df.index.max())

#  print the max index of multiclass_df
print(multiclass_df.index.max())

(122580, 77)
122579
153224


In [14]:
print(label_n)

[7 7 7 ... 3 3 3]


In [15]:
multiclass_df_copy = multiclass_df.copy()

multiclass_df_copy = multiclass_df_copy.drop(["ip.src_host", "ip.dst_host", "Attack_type"], axis=1)

# This is our copy of the data without IP addresses
scaled_features = StandardScaler().fit_transform(multiclass_df_copy.values)
X_train, X_test, y_train, y_test = train_test_split(scaled_features, label_n, stratify=label_n, test_size=0.2, random_state=42)

print ("Train:", X_train.shape, y_train.shape)
print ("Test:", X_test.shape, y_test.shape)


Train: (122580, 74) (122580,)
Test: (30645, 74) (30645,)


In [16]:
fl_X_train = []
fl_y_train = []

if METHOD == 'STRATIFIED':
    # Stratfiy the dataset
    from sklearn.model_selection import StratifiedKFold

    skf = StratifiedKFold(n_splits=NUM_OF_STRATIFIED_CLIENTS, shuffle=True, random_state=42)
    skf.get_n_splits(X_train, y_train)

    for _, train_index in skf.split(X_train, y_train):
        print("TRAIN:", train_index)
        X_np = X_train[train_index]
        y_np = y_train[train_index]

        fl_X_train.append(X_np)
        fl_y_train.append(y_np)

else: # UNUSED
    # Individual IP address
    for ip in known_sensor_ip_addresses:
        new_ip = [ip]
        print("new_ip:", new_ip)

        X_train_df['ip.src_host']
        
        print("Shape X_Train:", X_train.shape)
        print("Shape y_Train:", y_train.shape)

        # Filter dataframe by IP address
        new_df_src = X_train_df[ X_train_df['ip.src_host'].isin(new_ip) ]
        new_df_dst = X_train_df[ X_train_df['ip.dst_host'].isin(new_ip) ]

        print("Shape new_df_src:", new_df_src.shape)
        print("Shape new_df_dst:", new_df_dst.shape)

        X_np = np.vstack([ X_train[ new_df_src.index, : ], X_train[ new_df_dst.index, :] ])
        y_np = np.hstack([ y_train[ new_df_src.index ], y_train[ new_df_dst.index ] ])

        print ("x_np:", X_np.shape)
        print ("y_np:", y_np.shape)

        fl_X_train.append(X_np)
        fl_y_train.append(y_np)


TRAIN: [     0     19     25 ... 122549 122557 122567]
TRAIN: [     2     13     21 ... 122544 122568 122573]
TRAIN: [     6     12     20 ... 122574 122576 122577]
TRAIN: [    35     56     73 ... 122554 122565 122570]
TRAIN: [     3      4      5 ... 122536 122572 122579]
TRAIN: [     7     11     14 ... 122533 122563 122575]
TRAIN: [    10     50     61 ... 122561 122564 122571]
TRAIN: [     9     18     24 ... 122550 122555 122560]
TRAIN: [     1     15     26 ... 122547 122562 122569]
TRAIN: [    17     29     32 ... 122559 122566 122578]


In [17]:
# Print out the size of the fl_X_train
print ("fl_X_train size:", len(fl_X_train))

# Print out the size of each element in the fl_X_train
for i in range(len(fl_X_train)):
    print ("fl_X_train[", i, "]:", fl_X_train[i].shape)
    print ("fl_y_train[", i, "]:", fl_y_train[i].shape)


fl_X_train size: 10
fl_X_train[ 0 ]: (12258, 74)
fl_y_train[ 0 ]: (12258,)
fl_X_train[ 1 ]: (12258, 74)
fl_y_train[ 1 ]: (12258,)
fl_X_train[ 2 ]: (12258, 74)
fl_y_train[ 2 ]: (12258,)
fl_X_train[ 3 ]: (12258, 74)
fl_y_train[ 3 ]: (12258,)
fl_X_train[ 4 ]: (12258, 74)
fl_y_train[ 4 ]: (12258,)
fl_X_train[ 5 ]: (12258, 74)
fl_y_train[ 5 ]: (12258,)
fl_X_train[ 6 ]: (12258, 74)
fl_y_train[ 6 ]: (12258,)
fl_X_train[ 7 ]: (12258, 74)
fl_y_train[ 7 ]: (12258,)
fl_X_train[ 8 ]: (12258, 74)
fl_y_train[ 8 ]: (12258,)
fl_X_train[ 9 ]: (12258, 74)
fl_y_train[ 9 ]: (12258,)


In [18]:
len(label.unique()) 

15

In [19]:
NUM_OF_CLIENTS = len(fl_X_train)
print("NUM_OF_CLIENTS:", NUM_OF_CLIENTS)    

NUM_OF_ROUNDS = 15

print("Checking data split groups")
for i in range(len(fl_X_train)):
    print(i, ":", "X Shape", fl_X_train[i].shape, "Y Shape", fl_y_train[i].shape)

print("\nDeploy Simulation")


NUM_OF_CLIENTS: 10
Checking data split groups
0 : X Shape (12258, 74) Y Shape (12258,)
1 : X Shape (12258, 74) Y Shape (12258,)
2 : X Shape (12258, 74) Y Shape (12258,)
3 : X Shape (12258, 74) Y Shape (12258,)
4 : X Shape (12258, 74) Y Shape (12258,)
5 : X Shape (12258, 74) Y Shape (12258,)
6 : X Shape (12258, 74) Y Shape (12258,)
7 : X Shape (12258, 74) Y Shape (12258,)
8 : X Shape (12258, 74) Y Shape (12258,)
9 : X Shape (12258, 74) Y Shape (12258,)

Deploy Simulation


# FL Part

NOTE TO SELF - BUILD IN F1 SCORE  - https://www.kaggle.com/code/gpiosenka/flower-classification-f1-score-93


In [21]:
import os
import flwr as fl
import numpy as np
import tensorflow as tf

print('scikit-learn {}.'.format(sklearn.__version__))
print("flwr", fl.__version__)
print("numpy", np.__version__)
print("tf", tf.__version__)
# Make TensorFlow log less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation

class NumpyFlowerClient(fl.client.NumPyClient):
    def __init__(self, cid, model, train_data, train_labels):
        self.model = model
        self.cid = cid
        self.train_data = train_data
        self.train_labels = train_labels

    def get_parameters(self, config):
        return self.model.get_weights()

    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Training...")
        self.model.fit(self.train_data, self.train_labels, epochs=1, batch_size=32)
        print ("Client ", self.cid, "Training complete...")
        return self.model.get_weights(), len(self.train_data), {}

    def evaluate(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Evaluating...")
        loss, accuracy = self.model.evaluate(self.train_data, self.train_labels, batch_size=32)
        print ("Client ", self.cid, "Evaluating complete...", accuracy, loss)
        return loss, len(self.train_data), {"accuracy": accuracy}
    
    def predict(self, incoming):
        prediction = np.argmax( self.model.predict(incoming) ,axis=1)
        return prediction

def client_fn(cid: str) -> NumpyFlowerClient:
    """Create a Flower client representing a single organization."""

    # Load model
    #model = tf.keras.applications.MobileNetV2((32, 32, 3), classes=10, weights=None)
    #model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

    print ("Client ID:", cid)

    model = Sequential([
      #Flatten(input_shape=(79,1)),
      Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
      Dense(256, activation='sigmoid'),
      Dense(128, activation='sigmoid'), 
      #Dense(18, activation='sigmoid'),  
      Dense(len(label.unique()), activation='sigmoid')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

   
    partition_id = int(cid)
    X_train_c = fl_X_train[partition_id]
    y_train_c = fl_y_train[partition_id]

    # Create a  single Flower client representing a single organization
    return NumpyFlowerClient(cid, model, X_train_c, y_train_c)


print ("Deploy simulation...")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
eval_count = 0

def get_evaluate_fn(server_model):
    global eval_count
    """Return an evaluation function for server-side evaluation."""
    # The `evaluate` function will be called after every round
    
    
    def evaluate(server_round, parameters, config):
        global eval_count
        
        # Update model with the latest parameters
        server_model.set_weights(parameters)
        print ("Server Evaluating...", eval_count)
        loss, accuracy = server_model.evaluate(X_test, y_test)
        
        y_pred = server_model.predict(X_test)
        print ("Prediction: ", y_pred, y_pred.shape)
        #cmatrix = confusion_matrix(y_test, np.rint(y_pred))
        #print ("confusion_matrix:", cmatrix, cmatrix.shape)
                        
        print ("Server Evaluating complete...", accuracy, loss)
        
        np.save("y_pred-" + str(eval_count) + ".npy", y_pred)
        #np.save("cmatrix-" + str(eval_count) + ".npy", cmatrix)
        eval_count = eval_count + 1
        
        return loss, {"accuracy": accuracy}
    return evaluate



server_model = Sequential([
      #Flatten(input_shape=(79,1)),
      Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
      Dense(256, activation='sigmoid'),
      Dense(128, activation='sigmoid'), 
      #Dense(18, activation='sigmoid'),  
      Dense(len(label.unique()), activation='sigmoid')
    ])
server_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])



# Create FedAvg strategy
strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        fraction_evaluate=0.5,
        min_fit_clients=2, #10,
        min_evaluate_clients=2, #5,
        min_available_clients=2, #10,
        evaluate_fn=get_evaluate_fn(server_model),
        #evaluate_metrics_aggregation_fn=weighted_average,
)

# Start simulation
fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=NUM_OF_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=NUM_OF_ROUNDS),
    strategy=strategy,
)

INFO flwr 2023-07-06 14:44:46,807 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=15, round_timeout=None)


scikit-learn 1.2.0.
flwr 1.3.0
numpy 1.24.2
tf 2.11.0
Deploy simulation...


2023-07-06 14:44:50,749	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
INFO flwr 2023-07-06 14:44:54,003 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 24.0, 'object_store_memory': 6330243072.0, 'GPU': 1.0, 'memory': 12660486144.0, 'node:127.0.0.1': 1.0}
INFO flwr 2023-07-06 14:44:54,004 | server.py:86 | Initializing global parameters
INFO flwr 2023-07-06 14:44:54,005 | server.py:270 | Requesting initial parameters from one random client
INFO flwr 2023-07-06 14:44:58,633 | server.py:274 | Received initial parameters from one random client
INFO flwr 2023-07-06 14:44:58,634 | server.py:88 | Evaluating initial parameters


(launch_and_get_parameters pid=36636) Client ID: 3
Server Evaluating... 0
958/958 [==============================] - 1s 809us/step


INFO flwr 2023-07-06 14:45:01,065 | server.py:91 | initial parameters (loss, other metrics): 3.021543502807617, {'accuracy': 0.0017621145816519856}
INFO flwr 2023-07-06 14:45:01,067 | server.py:101 | FL starting
DEBUG flwr 2023-07-06 14:45:01,068 | server.py:215 | fit_round 1: strategy sampled 10 clients (out of 10)


Prediction:  [[0.6998283  0.7575276  0.29630598 ... 0.5778504  0.5448724  0.6755301 ]
 [0.7209097  0.7605257  0.27230492 ... 0.5821651  0.49488848 0.6197814 ]
 [0.70457953 0.7569488  0.30105686 ... 0.5893093  0.54245114 0.67587   ]
 ...
 [0.6717604  0.7097229  0.2929261  ... 0.56384075 0.53256845 0.6881053 ]
 [0.6995239  0.75880796 0.29787987 ... 0.5787805  0.5380494  0.67405623]
 [0.6944363  0.76119184 0.29786608 ... 0.57246894 0.538171   0.66999996]] (30645, 15)
Server Evaluating complete... 0.0017621145816519856 3.021543502807617
(launch_and_fit pid=36636) Client ID: 0
(launch_and_fit pid=36636) Client  0 Training...
(launch_and_fit pid=36636) 
(launch_and_fit pid=36636)   1/384 [..............................] - ETA: 4:34 - loss: 2.9890 - accuracy: 0.0000e+00
(launch_and_fit pid=36636)  32/384 [=>............................] - ETA: 0s - loss: 2.4158 - accuracy: 0.1836      
(launch_and_fit pid=36636)  64/384 [====>.........................] - ETA: 0s - loss: 2.2055 - accuracy: 0.2

DEBUG flwr 2023-07-06 14:45:09,061 | server.py:229 | fit_round 1 received 10 results and 0 failures
WARNING flwr 2023-07-06 14:45:09,075 | fedavg.py:242 | No fit_metrics_aggregation_fn provided


(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 383/384 [============================>.] - ETA: 0s - loss: 1.1845 - accuracy: 0.5878
(launch_and_fit pid=52824) 384/384 [==============================] - 2s 2ms/step - loss: 1.1844 - accuracy: 0.5879
(launch_and_fit pid=52824) Client  5 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 2s 2ms/step - loss: 1.1958 - accuracy: 0.5880
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 384/384 [==============================] - 2s 2ms/step - loss: 1.1984 - accuracy: 0.5861
(launch_and_fit pid=49088) Client  9 Training complete...
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 384/384 [==============================] - 2s 2ms/step - loss: 1.2087 - accuracy: 0.5913
(launch_and_fit pid=38564) Client  6 Training complete...
(launch_and_fit pid=54948) Client  3 Training complete...
Server Evaluating... 1
958/958 [==============================] - 1s 823us/step


INFO flwr 2023-07-06 14:45:11,131 | server.py:116 | fit progress: (1, 0.659288763999939, {'accuracy': 0.6982868313789368}, 10.06350620000012)
DEBUG flwr 2023-07-06 14:45:11,132 | server.py:165 | evaluate_round 1: strategy sampled 5 clients (out of 10)


Prediction:  [[0.17508584 0.3690127  0.4320578  ... 0.9640026  0.2690637  0.5092601 ]
 [0.99897754 0.59604454 0.1738613  ... 0.2538462  0.25237763 0.45177323]
 [0.9987649  0.7486437  0.15074934 ... 0.2206724  0.23979719 0.40677878]
 ...
 [0.9989501  0.5884402  0.16000006 ... 0.2660408  0.20937169 0.43983844]
 [0.27918154 0.9650385  0.07714686 ... 0.31799906 0.14346136 0.1097212 ]
 [0.12493767 0.43297493 0.5038404  ... 0.9647396  0.24877693 0.49119282]] (30645, 15)
Server Evaluating complete... 0.6982868313789368 0.659288763999939
(launch_and_evaluate pid=54948) Client ID: 9
(launch_and_evaluate pid=54948) Client  9 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 3
(launch_and_evaluate pid=49088) Client  3 Evaluating...
(launch_and_evaluate pid=54092) Client ID: 8
(launch_and_evaluate pid=54092) Client  8 Evaluating...
(launch_and_evaluate pid=38564) Client ID: 4
(launch_and_evaluate pid=38564) Client  4 Evaluating...
(launch_and_evaluate pid=52824) Client ID: 7
(launch_and_eva

DEBUG flwr 2023-07-06 14:45:11,943 | server.py:179 | evaluate_round 1 received 5 results and 0 failures
WARNING flwr 2023-07-06 14:45:11,944 | fedavg.py:273 | No evaluate_metrics_aggregation_fn provided
DEBUG flwr 2023-07-06 14:45:11,944 | server.py:215 | fit_round 2: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 260/384 [===================>..........] - ETA: 0s - loss: 0.6485 - accuracy: 0.6975
(launch_and_evaluate pid=54948) 304/384 [======================>.......] - ETA: 0s - loss: 0.6500 - accuracy: 0.7001
(launch_and_evaluate pid=54948) 349/384 [==========================>...] - ETA: 0s - loss: 0.6496 - accuracy: 0.7027
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 268/384 [===================>..........] - ETA: 0s - loss: 0.6577 - accuracy: 0.6922
(launch_and_evaluate pid=49088) 314/384 [=======================>......] - ETA: 0s - loss: 0.6550 - accuracy: 0.6946
(launch_and_evaluate pid=54092) 
(launch_and_evaluate pid=54092) 258/384 [===================>..........] - ETA: 0s - loss: 0.6698 - accuracy: 0.6927
(launch_and_evaluate pid=54092) 303/384 [======================>.......] - ETA: 0s - loss: 0.6709 - accuracy: 0.6898
(launch_and_evaluate pid=54092) 347/384 [==========================>...] - ETA: 0s

DEBUG flwr 2023-07-06 14:45:13,714 | server.py:229 | fit_round 2 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 292/384 [=====================>........] - ETA: 0s - loss: 0.6265 - accuracy: 0.6896
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 302/384 [======================>.......] - ETA: 0s - loss: 0.6246 - accuracy: 0.6875
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 340/384 [=========================>....] - ETA: 0s - loss: 0.6177 - accuracy: 0.6848
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 339/384 [=========================>....] - ETA: 0s - loss: 0.6277 - accuracy: 0.6907
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 365/384 [===========================>..] - ETA: 0s - loss: 0.6102 - accuracy: 0.6957
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 325/384 [========================>.....] - ETA: 0s - loss: 0.6182 - accuracy: 0.6950
(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 330/384 [========================>.....] - ETA: 0s - loss: 0.6072 - accuracy: 0.6916
(launch_and_fit pid=

INFO flwr 2023-07-06 14:45:15,830 | server.py:116 | fit progress: (2, 0.5745646357536316, {'accuracy': 0.7245553731918335}, 14.762395800000377)
DEBUG flwr 2023-07-06 14:45:15,831 | server.py:165 | evaluate_round 2: strategy sampled 5 clients (out of 10)


Prediction:  [[0.02580853 0.16391188 0.10383629 ... 0.9729115  0.07916225 0.28234726]
 [0.99979335 0.30922005 0.05405256 ... 0.10540441 0.09129571 0.37798715]
 [0.99982196 0.6264814  0.0435543  ... 0.06626473 0.10348286 0.29779017]
 ...
 [0.99983245 0.29816905 0.05084016 ... 0.10101535 0.07967121 0.38520008]
 [0.07496937 0.9823143  0.02296943 ... 0.10349907 0.04564996 0.04088427]
 [0.01401939 0.20264766 0.15598421 ... 0.9772058  0.05493249 0.23549624]] (30645, 15)
Server Evaluating complete... 0.7245553731918335 0.5745646357536316
(launch_and_evaluate pid=36636) Client ID: 5
(launch_and_evaluate pid=36636) Client  5 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 7
(launch_and_evaluate pid=54948) Client  7 Evaluating...
(launch_and_evaluate pid=26420) Client ID: 1
(launch_and_evaluate pid=26420) Client  1 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 3
(launch_and_evaluate pid=49088) Client  3 Evaluating...
(launch_and_evaluate pid=52824) Client ID: 6
(launch_and_ev

DEBUG flwr 2023-07-06 14:45:16,618 | server.py:179 | evaluate_round 2 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:16,619 | server.py:215 | fit_round 3: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 273/384 [====================>.........] - ETA: 0s - loss: 0.5750 - accuracy: 0.7181
(launch_and_evaluate pid=52824) 
(launch_and_evaluate pid=52824) 272/384 [====================>.........] - ETA: 0s - loss: 0.5786 - accuracy: 0.7216
(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 266/384 [===================>..........] - ETA: 0s - loss: 0.5757 - accuracy: 0.7232
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 265/384 [===================>..........] - ETA: 0s - loss: 0.5730 - accuracy: 0.7261
(launch_and_evaluate pid=26420) 
(launch_and_evaluate pid=26420) 263/384 [===================>..........] - ETA: 0s - loss: 0.5721 - accuracy: 0.7235
(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 308/384 [=======================>......] - ETA: 0s - loss: 0.5727 - accuracy: 0.7255
(launch_and_evaluate pid=36636) 355/384 [==========================>...] - ETA: 0s - loss: 0.5709 - 

DEBUG flwr 2023-07-06 14:45:18,310 | server.py:229 | fit_round 3 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 364/384 [===========================>..] - ETA: 0s - loss: 0.5717 - accuracy: 0.7041
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 368/384 [===========================>..] - ETA: 0s - loss: 0.5678 - accuracy: 0.7064
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 372/384 [============================>.] - ETA: 0s - loss: 0.5705 - accuracy: 0.7128
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 363/384 [===========================>..] - ETA: 0s - loss: 0.5805 - accuracy: 0.6971
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 328/384 [========================>.....] - ETA: 0s - loss: 0.5817 - accuracy: 0.6990
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 384/384 [==============================] - 1s 2ms/step - loss: 0.5709 - accuracy: 0.7119
(launch_and_fit pid=36820) Client  7 Training complete...
(launch_and_fit pid=32936) 
(launch_and_fit pid=32936) 362/384 [===========================>..] - 

INFO flwr 2023-07-06 14:45:20,339 | server.py:116 | fit progress: (3, 0.550567626953125, {'accuracy': 0.7116332054138184}, 19.270700100001704)
DEBUG flwr 2023-07-06 14:45:20,340 | server.py:165 | evaluate_round 3: strategy sampled 5 clients (out of 10)


Prediction:  [[0.00527919 0.11219275 0.04522306 ... 0.9779069  0.05208588 0.17560658]
 [0.9999013  0.2133776  0.02609508 ... 0.05753469 0.0597189  0.28834638]
 [0.99993867 0.61688966 0.0213992  ... 0.033014   0.07807316 0.21122368]
 ...
 [0.9999324  0.19413435 0.02614894 ... 0.05179447 0.05503276 0.31589255]
 [0.02423403 0.98875684 0.01243754 ... 0.06185942 0.02833514 0.01654302]
 [0.0024763  0.14160934 0.07107683 ... 0.98144394 0.03283364 0.12843269]] (30645, 15)
Server Evaluating complete... 0.7116332054138184 0.550567626953125
(launch_and_evaluate pid=32936) Client ID: 5
(launch_and_evaluate pid=36612) Client ID: 8
(launch_and_evaluate pid=54092) Client ID: 4
(launch_and_evaluate pid=38564) Client ID: 1
(launch_and_evaluate pid=38564) Client  1 Evaluating...
(launch_and_evaluate pid=52824) Client ID: 0
(launch_and_evaluate pid=54092) Client  4 Evaluating...
(launch_and_evaluate pid=52824) Client  0 Evaluating...
(launch_and_evaluate pid=32936) Client  5 Evaluating...
(launch_and_eva

DEBUG flwr 2023-07-06 14:45:21,110 | server.py:179 | evaluate_round 3 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:21,111 | server.py:215 | fit_round 4: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=32936) 
(launch_and_evaluate pid=32936) 229/384 [================>.............] - ETA: 0s - loss: 0.5516 - accuracy: 0.7140
(launch_and_evaluate pid=32936) 276/384 [====================>.........] - ETA: 0s - loss: 0.5499 - accuracy: 0.7114
(launch_and_evaluate pid=32936) 324/384 [========================>.....] - ETA: 0s - loss: 0.5478 - accuracy: 0.7104
(launch_and_evaluate pid=36612) 
(launch_and_evaluate pid=36612) 233/384 [=================>............] - ETA: 0s - loss: 0.5634 - accuracy: 0.7082
(launch_and_evaluate pid=36612) 280/384 [====================>.........] - ETA: 0s - loss: 0.5636 - accuracy: 0.7049
(launch_and_evaluate pid=36612) 329/384 [========================>.....] - ETA: 0s - loss: 0.5618 - accuracy: 0.7053
(launch_and_evaluate pid=54092) 
(launch_and_evaluate pid=54092) 277/384 [====================>.........] - ETA: 0s - loss: 0.5501 - accuracy: 0.7075
(launch_and_evaluate pid=54092) 322/384 [========================>.....] - ETA: 0s

DEBUG flwr 2023-07-06 14:45:23,153 | server.py:229 | fit_round 4 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7125
(launch_and_fit pid=36636) Client  5 Training complete...
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 368/384 [===========================>..] - ETA: 0s - loss: 0.5577 - accuracy: 0.7138
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 376/384 [============================>.] - ETA: 0s - loss: 0.5535 - accuracy: 0.7089
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 384/384 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7139
(launch_and_fit pid=49088) Client  7 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7080
(launch_and_fit pid=54948) Client  3 Training complete...
Server Evaluating... 4
958/958 [==============================] - 1s 824us/step


INFO flwr 2023-07-06 14:45:25,229 | server.py:116 | fit progress: (4, 0.5368147492408752, {'accuracy': 0.7164953351020813}, 24.161652900002082)
DEBUG flwr 2023-07-06 14:45:25,230 | server.py:165 | evaluate_round 4: strategy sampled 5 clients (out of 10)


Prediction:  [[1.25756976e-03 7.99931437e-02 3.70137915e-02 ... 9.81073201e-01
  2.77922060e-02 1.34883508e-01]
 [9.99922514e-01 1.25882670e-01 2.28485782e-02 ... 3.95065621e-02
  3.26358005e-02 2.45892629e-01]
 [9.99970555e-01 5.75374365e-01 1.90424360e-02 ... 2.15781331e-02
  5.18235564e-02 1.79757625e-01]
 ...
 [9.99957144e-01 1.03702731e-01 2.57353652e-02 ... 3.41832377e-02
  3.30672376e-02 2.98694551e-01]
 [9.47510079e-03 9.90223229e-01 1.21309990e-02 ... 5.18284217e-02
  1.47124035e-02 9.80042852e-03]
 [5.82459033e-04 9.50754285e-02 5.33181280e-02 ... 9.83804166e-01
  1.70811228e-02 9.09542665e-02]] (30645, 15)
Server Evaluating complete... 0.7164953351020813 0.5368147492408752
(launch_and_evaluate pid=36636) Client ID: 7
(launch_and_evaluate pid=36636) Client  7 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 2
(launch_and_evaluate pid=54948) Client  2 Evaluating...
(launch_and_evaluate pid=26420) Client ID: 8
(launch_and_evaluate pid=26420) Client  8 Evaluating...
(lau

DEBUG flwr 2023-07-06 14:45:25,975 | server.py:179 | evaluate_round 4 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:25,976 | server.py:215 | fit_round 5: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 282/384 [=====================>........] - ETA: 0s - loss: 0.5369 - accuracy: 0.7151
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 287/384 [=====================>........] - ETA: 0s - loss: 0.5377 - accuracy: 0.7158
(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 281/384 [====================>.........] - ETA: 0s - loss: 0.5356 - accuracy: 0.7209
(launch_and_evaluate pid=38564) 
(launch_and_evaluate pid=38564) 280/384 [====================>.........] - ETA: 0s - loss: 0.5362 - accuracy: 0.7135
(launch_and_evaluate pid=26420) 
(launch_and_evaluate pid=26420) 283/384 [=====================>........] - ETA: 0s - loss: 0.5492 - accuracy: 0.7141
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 328/384 [========================>.....] - ETA: 0s - loss: 0.5396 - accuracy: 0.7126
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 334/384 [=========================>

DEBUG flwr 2023-07-06 14:45:28,083 | server.py:229 | fit_round 5 received 10 results and 0 failures


(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 384/384 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7149
(launch_and_fit pid=52824) Client  3 Training complete...
(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 362/384 [===========================>..] - ETA: 0s - loss: 0.5416 - accuracy: 0.7210
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 384/384 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7234
(launch_and_fit pid=36612) Client  9 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7179
(launch_and_fit pid=54948) Client  5 Training complete...
(launch_and_fit pid=26420) 
(launch_and_fit pid=26420) 381/384 [============================>.] - ETA: 0s - loss: 0.5542 - accuracy: 0.7128
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 384/384 [==============================] - 1s 2ms/step - lo

INFO flwr 2023-07-06 14:45:30,060 | server.py:116 | fit progress: (5, 0.5273430347442627, {'accuracy': 0.7235438227653503}, 28.993036899999424)
DEBUG flwr 2023-07-06 14:45:30,061 | server.py:165 | evaluate_round 5: strategy sampled 5 clients (out of 10)


Prediction:  [[5.0626660e-04 6.0790971e-02 3.0846648e-02 ... 9.8244232e-01
  1.9852988e-02 1.0856919e-01]
 [9.9996871e-01 1.0646242e-01 2.0249691e-02 ... 2.7998926e-02
  2.5607556e-02 2.0708779e-01]
 [9.9999321e-01 5.9409571e-01 1.6543610e-02 ... 1.6407635e-02
  4.6248890e-02 1.5574504e-01]
 ...
 [9.9998528e-01 7.6287657e-02 2.4450094e-02 ... 2.2969464e-02
  2.7447630e-02 2.7105317e-01]
 [7.8383600e-03 9.9184495e-01 9.4943736e-03 ... 4.7410872e-02
  1.0767372e-02 6.2261350e-03]
 [2.4171721e-04 6.7008607e-02 3.8026176e-02 ... 9.8472917e-01
  1.2719456e-02 7.1035475e-02]] (30645, 15)
Server Evaluating complete... 0.7235438227653503 0.5273430347442627
(launch_and_evaluate pid=36636) Client ID: 8
(launch_and_evaluate pid=36636) Client  8 Evaluating...
(launch_and_evaluate pid=32936) Client ID: 7
(launch_and_evaluate pid=32936) Client  7 Evaluating...
(launch_and_evaluate pid=26420) Client ID: 1
(launch_and_evaluate pid=26420) Client  1 Evaluating...
(launch_and_evaluate pid=49088) Client I

DEBUG flwr 2023-07-06 14:45:30,775 | server.py:179 | evaluate_round 5 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:30,776 | server.py:215 | fit_round 6: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 191/384 [=============>................] - ETA: 0s - loss: 0.5433 - accuracy: 0.7196
(launch_and_evaluate pid=36636) 237/384 [=================>............] - ETA: 0s - loss: 0.5385 - accuracy: 0.7226
(launch_and_evaluate pid=36636) 286/384 [=====================>........] - ETA: 0s - loss: 0.5401 - accuracy: 0.7190
(launch_and_evaluate pid=32936) 
(launch_and_evaluate pid=32936) 192/384 [==============>...............] - ETA: 0s - loss: 0.5300 - accuracy: 0.7197
(launch_and_evaluate pid=32936) 240/384 [=================>............] - ETA: 0s - loss: 0.5259 - accuracy: 0.7240
(launch_and_evaluate pid=32936) 291/384 [=====================>........] - ETA: 0s - loss: 0.5253 - accuracy: 0.7258
(launch_and_evaluate pid=26420) 
(launch_and_evaluate pid=26420) 189/384 [=============>................] - ETA: 0s - loss: 0.5349 - accuracy: 0.7188
(launch_and_evaluate pid=26420) 235/384 [=================>............] - ETA: 0s

DEBUG flwr 2023-07-06 14:45:32,446 | server.py:229 | fit_round 6 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7114
(launch_and_fit pid=36636) Client  6 Training complete...
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 376/384 [============================>.] - ETA: 0s - loss: 0.5402 - accuracy: 0.7164
(launch_and_fit pid=54092) 384/384 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7157
(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 380/384 [============================>.] - ETA: 0s - loss: 0.5425 - accuracy: 0.7146
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 365/384 [===========================>..] - ETA: 0s - loss: 0.5347 - accuracy: 0.7155
(launch_and_fit pid=54092) Client  0 Training complete...
(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 384/384 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7145
(launch_and_fit pid=52824) Client  2 Training complete...
Se

INFO flwr 2023-07-06 14:45:34,421 | server.py:116 | fit progress: (6, 0.5202458500862122, {'accuracy': 0.7213574647903442}, 33.35405630000241)
DEBUG flwr 2023-07-06 14:45:34,422 | server.py:165 | evaluate_round 6: strategy sampled 5 clients (out of 10)


Prediction:  [[1.20464676e-04 5.08480966e-02 2.84689795e-02 ... 9.81028318e-01
  1.43203698e-02 8.17878395e-02]
 [9.99901056e-01 1.10856675e-01 2.08795480e-02 ... 2.33630426e-02
  2.52232198e-02 1.66336104e-01]
 [9.99986708e-01 6.78289711e-01 1.76482648e-02 ... 1.30212326e-02
  4.63188104e-02 1.27175078e-01]
 ...
 [9.99959409e-01 7.04809353e-02 2.68280748e-02 ... 1.64533909e-02
  2.73361690e-02 2.26076663e-01]
 [2.25064252e-03 9.93299782e-01 9.38458182e-03 ... 3.65528725e-02
  8.69589951e-03 3.99909215e-03]
 [5.86470560e-05 5.44086285e-02 3.19374129e-02 ... 9.83211517e-01
  9.18556191e-03 5.09659424e-02]] (30645, 15)
Server Evaluating complete... 0.7213574647903442 0.5202458500862122
(launch_and_evaluate pid=36636) Client ID: 5
(launch_and_evaluate pid=36636) Client  5 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 0
(launch_and_evaluate pid=36612) Client ID: 3
(launch_and_evaluate pid=36612) Client  3 Evaluating...
(launch_and_evaluate pid=54092) Client ID: 7
(launch_and_eva

DEBUG flwr 2023-07-06 14:45:35,229 | server.py:179 | evaluate_round 6 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:35,230 | server.py:215 | fit_round 7: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 253/384 [==================>...........] - ETA: 0s - loss: 0.5205 - accuracy: 0.7205
(launch_and_evaluate pid=36636) 295/384 [======================>.......] - ETA: 0s - loss: 0.5174 - accuracy: 0.7213
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 250/384 [==================>...........] - ETA: 0s - loss: 0.5210 - accuracy: 0.7139
(launch_and_evaluate pid=54948) 291/384 [=====================>........] - ETA: 0s - loss: 0.5217 - accuracy: 0.7146
(launch_and_evaluate pid=36612) 
(launch_and_evaluate pid=36612) 252/384 [==================>...........] - ETA: 0s - loss: 0.5222 - accuracy: 0.7150
(launch_and_evaluate pid=36612) 291/384 [=====================>........] - ETA: 0s - loss: 0.5237 - accuracy: 0.7114
(launch_and_evaluate pid=54092) 
(launch_and_evaluate pid=54092) 261/384 [===================>..........] - ETA: 0s - loss: 0.5175 - accuracy: 0.7269
(launch_and_evaluate pid=54092) 303/384 [========

DEBUG flwr 2023-07-06 14:45:37,054 | server.py:229 | fit_round 7 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 373/384 [============================>.] - ETA: 0s - loss: 0.5316 - accuracy: 0.7249
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 384/384 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7216
(launch_and_fit pid=36820) Client  3 Training complete...
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 366/384 [===========================>..] - ETA: 0s - loss: 0.5243 - accuracy: 0.7275
(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7260
(launch_and_fit pid=36636) Client  7 Training complete...
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 369/384 [===========================>..] - ETA: 0s - loss: 0.5338 - accuracy: 0.7149
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 376/384 [============================>.] - ETA: 0s - loss: 0.5256 - accuracy: 0.7255
(launch_and_fit pid=38564) 
(launch_

INFO flwr 2023-07-06 14:45:39,146 | server.py:116 | fit progress: (7, 0.5157963633537292, {'accuracy': 0.7225974798202515}, 38.07858860000124)
DEBUG flwr 2023-07-06 14:45:39,147 | server.py:165 | evaluate_round 7: strategy sampled 5 clients (out of 10)


Prediction:  [[5.89556257e-05 3.54720466e-02 2.35075355e-02 ... 9.82827187e-01
  1.20119676e-02 6.43827468e-02]
 [9.99936104e-01 9.12415683e-02 1.63304750e-02 ... 2.80392971e-02
  2.46446282e-02 1.38023376e-01]
 [9.99994934e-01 6.89302266e-01 1.58701707e-02 ... 1.35399727e-02
  5.11302277e-02 1.09495886e-01]
 ...
 [9.99972165e-01 5.23362495e-02 2.26439498e-02 ... 1.68888774e-02
  2.72716694e-02 1.89759925e-01]
 [1.97126134e-03 9.93333459e-01 6.71789004e-03 ... 3.86397243e-02
  7.32524693e-03 2.63374625e-03]
 [2.96649632e-05 3.57628092e-02 2.39130706e-02 ... 9.84727144e-01
  7.94224255e-03 3.98868397e-02]] (30645, 15)
Server Evaluating complete... 0.7225974798202515 0.5157963633537292
(launch_and_evaluate pid=36636) Client ID: 5
(launch_and_evaluate pid=36636) Client  5 Evaluating...
(launch_and_evaluate pid=36820) Client ID: 2
(launch_and_evaluate pid=36820) Client  2 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 9
(launch_and_evaluate pid=49088) Client  9 Evaluating...
(lau

DEBUG flwr 2023-07-06 14:45:39,962 | server.py:179 | evaluate_round 7 received 5 results and 0 failures


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 176/384 [============>.................] - ETA: 0s - loss: 0.5204 - accuracy: 0.7198
(launch_and_evaluate pid=36636) 221/384 [================>.............] - ETA: 0s - loss: 0.5169 - accuracy: 0.7245
(launch_and_evaluate pid=36820) 
(launch_and_evaluate pid=36820) 132/384 [=========>....................] - ETA: 0s - loss: 0.5157 - accuracy: 0.7225
(launch_and_evaluate pid=36820) 178/384 [============>.................] - ETA: 0s - loss: 0.5177 - accuracy: 0.7228
(launch_and_evaluate pid=36820) 225/384 [================>.............] - ETA: 0s - loss: 0.5201 - accuracy: 0.7210
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 178/384 [============>.................] - ETA: 0s - loss: 0.4987 - accuracy: 0.7265
(launch_and_evaluate pid=49088) 222/384 [================>.............] - ETA: 0s - loss: 0.5050 - accuracy: 0.7261
(launch_and_evaluate pid=49088) 269/384 [====================>.........] - ETA: 0s

DEBUG flwr 2023-07-06 14:45:39,963 | server.py:215 | fit_round 8: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 352/384 [==========================>...] - ETA: 0s - loss: 0.5116 - accuracy: 0.7243
(launch_and_evaluate pid=36636) 384/384 [==============================] - 1s 1ms/step - loss: 0.5115 - accuracy: 0.7238
(launch_and_evaluate pid=36636) Client  5 Evaluating complete... 0.7237722277641296 0.5115086436271667
(launch_and_evaluate pid=36820) 
(launch_and_evaluate pid=36820) 313/384 [=======================>......] - ETA: 0s - loss: 0.5176 - accuracy: 0.7186
(launch_and_evaluate pid=36820) 358/384 [==========================>...] - ETA: 0s - loss: 0.5192 - accuracy: 0.7160
(launch_and_evaluate pid=36820) 384/384 [==============================] - 1s 1ms/step - loss: 0.5205 - accuracy: 0.7145
(launch_and_evaluate pid=36820) Client  2 Evaluating complete... 0.7144721746444702 0.5205245018005371
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 353/384 [==========================>...] - ETA: 0s - loss: 0.5061 - ac

DEBUG flwr 2023-07-06 14:45:41,596 | server.py:229 | fit_round 8 received 10 results and 0 failures


(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 373/384 [============================>.] - ETA: 0s - loss: 0.5241 - accuracy: 0.7193
(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 384/384 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7254
(launch_and_fit pid=52824) Client  9 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7199
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 384/384 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7233
(launch_and_fit pid=36612) Client  7 Training complete...
(launch_and_fit pid=54948) Client  5 Training complete...
Server Evaluating... 8
958/958 [==============================] - 1s 826us/step


INFO flwr 2023-07-06 14:45:43,633 | server.py:116 | fit progress: (8, 0.5118222236633301, {'accuracy': 0.7227280139923096}, 42.56531360000008)
DEBUG flwr 2023-07-06 14:45:43,634 | server.py:165 | evaluate_round 8: strategy sampled 5 clients (out of 10)


Prediction:  [[4.02631631e-05 3.15127969e-02 2.31229309e-02 ... 9.82090414e-01
  8.38383846e-03 5.35608009e-02]
 [9.99954343e-01 1.00202344e-01 1.60819311e-02 ... 2.97226794e-02
  1.96828861e-02 1.20313741e-01]
 [9.99997139e-01 7.70119607e-01 1.79410726e-02 ... 1.27041489e-02
  4.77984771e-02 9.34308395e-02]
 ...
 [9.99976158e-01 5.34666628e-02 2.34844517e-02 ... 1.55718541e-02
  2.21394058e-02 1.64931640e-01]
 [2.54223053e-03 9.94678140e-01 7.67127750e-03 ... 3.70968655e-02
  5.73407626e-03 2.02360493e-03]
 [1.94823988e-05 3.11458260e-02 2.27364823e-02 ... 9.84389901e-01
  5.46210771e-03 3.22806202e-02]] (30645, 15)
Server Evaluating complete... 0.7227280139923096 0.5118222236633301
(launch_and_evaluate pid=54948) Client ID: 4
(launch_and_evaluate pid=49088) Client ID: 0
(launch_and_evaluate pid=36612) Client ID: 3
(launch_and_evaluate pid=38564) Client ID: 8
(launch_and_evaluate pid=52824) Client ID: 2
(launch_and_evaluate pid=54948) Client  4 Evaluating...
(launch_and_evaluate pid=4

DEBUG flwr 2023-07-06 14:45:44,645 | server.py:179 | evaluate_round 8 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:44,646 | server.py:215 | fit_round 9: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 271/384 [====================>.........] - ETA: 0s - loss: 0.5114 - accuracy: 0.7145
(launch_and_evaluate pid=54948) 319/384 [=======================>......] - ETA: 0s - loss: 0.5098 - accuracy: 0.7177
(launch_and_evaluate pid=54948) 368/384 [===========================>..] - ETA: 0s - loss: 0.5084 - accuracy: 0.7182
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 267/384 [===================>..........] - ETA: 0s - loss: 0.5136 - accuracy: 0.7156
(launch_and_evaluate pid=49088) 318/384 [=======================>......] - ETA: 0s - loss: 0.5169 - accuracy: 0.7140
(launch_and_evaluate pid=49088) 369/384 [===========================>..] - ETA: 0s - loss: 0.5147 - accuracy: 0.7161
(launch_and_evaluate pid=36612) 
(launch_and_evaluate pid=36612) 274/384 [====================>.........] - ETA: 0s - loss: 0.5160 - accuracy: 0.7154
(launch_and_evaluate pid=36612) 322/384 [========================>.....] - ETA: 0s

DEBUG flwr 2023-07-06 14:45:46,279 | server.py:229 | fit_round 9 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7275
(launch_and_fit pid=36636) Client  3 Training complete...
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 384/384 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7340
(launch_and_fit pid=49088) Client  9 Training complete...
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 384/384 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7243
(launch_and_fit pid=54092) Client  4 Training complete...
Server Evaluating... 9
958/958 [==============================] - 1s 841us/step


INFO flwr 2023-07-06 14:45:48,350 | server.py:116 | fit progress: (9, 0.5099111795425415, {'accuracy': 0.723086953163147}, 47.28303220000089)
DEBUG flwr 2023-07-06 14:45:48,351 | server.py:165 | evaluate_round 9: strategy sampled 5 clients (out of 10)


Prediction:  [[3.18879174e-05 2.46602669e-02 1.90153737e-02 ... 9.80566263e-01
  7.74711231e-03 4.66649234e-02]
 [9.99955893e-01 9.82091501e-02 1.79288499e-02 ... 3.09197512e-02
  2.60375496e-02 1.30203396e-01]
 [9.99998271e-01 8.20157766e-01 2.20090263e-02 ... 1.19963931e-02
  6.84335902e-02 1.01044044e-01]
 ...
 [9.99974787e-01 5.07482812e-02 2.71426570e-02 ... 1.46032665e-02
  2.83699762e-02 1.71929941e-01]
 [3.06586456e-03 9.94761169e-01 7.34979846e-03 ... 3.28956097e-02
  6.29473198e-03 1.80732016e-03]
 [1.49247262e-05 2.40699723e-02 1.83515437e-02 ... 9.83016133e-01
  5.11017907e-03 2.80884150e-02]] (30645, 15)
Server Evaluating complete... 0.723086953163147 0.5099111795425415
(launch_and_evaluate pid=36636) Client ID: 9
(launch_and_evaluate pid=36636) Client  9 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 8
(launch_and_evaluate pid=54948) Client  8 Evaluating...
(launch_and_evaluate pid=26420) Client ID: 0
(launch_and_evaluate pid=26420) Client  0 Evaluating...
(laun

DEBUG flwr 2023-07-06 14:45:49,092 | server.py:179 | evaluate_round 9 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:49,093 | server.py:215 | fit_round 10: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 327/384 [========================>.....] - ETA: 0s - loss: 0.4995 - accuracy: 0.7295
(launch_and_evaluate pid=36636) 376/384 [============================>.] - ETA: 0s - loss: 0.5013 - accuracy: 0.7285
(launch_and_evaluate pid=36636) 384/384 [==============================] - 1s 1ms/step - loss: 0.5023 - accuracy: 0.7279
(launch_and_evaluate pid=36636) Client  9 Evaluating complete... 0.7278512120246887 0.5022662878036499
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 326/384 [========================>.....] - ETA: 0s - loss: 0.5195 - accuracy: 0.7240
(launch_and_evaluate pid=54948) 374/384 [============================>.] - ETA: 0s - loss: 0.5180 - accuracy: 0.7231
(launch_and_evaluate pid=54948) 384/384 [==============================] - 1s 1ms/step - loss: 0.5177 - accuracy: 0.7230
(launch_and_evaluate pid=54948) Client  8 Evaluating complete... 0.7229564189910889 0.5176901817321777
(launch_and_evalua

DEBUG flwr 2023-07-06 14:45:50,799 | server.py:229 | fit_round 10 received 10 results and 0 failures


(launch_and_fit pid=32936) 
(launch_and_fit pid=32936) 359/384 [===========================>..] - ETA: 0s - loss: 0.5203 - accuracy: 0.7276
(launch_and_fit pid=26420) Client  0 Training complete...
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 366/384 [===========================>..] - ETA: 0s - loss: 0.5271 - accuracy: 0.7147
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 360/384 [===========================>..] - ETA: 0s - loss: 0.5189 - accuracy: 0.7280
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 324/384 [========================>.....] - ETA: 0s - loss: 0.5300 - accuracy: 0.7294
(launch_and_fit pid=54948) Client  3 Training complete...
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 384/384 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7149
(launch_and_fit pid=36612) Client  6 Training complete...
(launch_and_fit pid=52824) 
(launch_and_fit pid=52824) 383/384 [============================>.] - ETA: 0s - loss: 0.5285 -

INFO flwr 2023-07-06 14:45:52,798 | server.py:116 | fit progress: (10, 0.5064926147460938, {'accuracy': 0.7239353656768799}, 51.72994280000057)
DEBUG flwr 2023-07-06 14:45:52,799 | server.py:165 | evaluate_round 10: strategy sampled 5 clients (out of 10)


Prediction:  [[2.8869588e-05 2.0620720e-02 1.8211173e-02 ... 9.8172677e-01
  6.0640168e-03 4.0405825e-02]
 [9.9996126e-01 1.2397552e-01 1.7044134e-02 ... 3.7537858e-02
  2.9783502e-02 1.2641783e-01]
 [9.9999881e-01 8.7325597e-01 2.4348335e-02 ... 1.2623969e-02
  8.4332533e-02 9.9572584e-02]
 ...
 [9.9997628e-01 6.3886851e-02 2.7654938e-02 ... 1.6407626e-02
  3.2087166e-02 1.6487321e-01]
 [4.3497095e-03 9.9510163e-01 5.9744879e-03 ... 3.3510029e-02
  5.3592529e-03 1.4457790e-03]
 [1.2724861e-05 2.0066252e-02 1.7331503e-02 ... 9.8425943e-01
  3.9926441e-03 2.4093442e-02]] (30645, 15)
Server Evaluating complete... 0.7239353656768799 0.5064926147460938
(launch_and_evaluate pid=36636) Client ID: 6
(launch_and_evaluate pid=36636) Client  6 Evaluating...
(launch_and_evaluate pid=32936) Client ID: 3
(launch_and_evaluate pid=32936) Client  3 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 4
(launch_and_evaluate pid=49088) Client  4 Evaluating...
(launch_and_evaluate pid=54092) Client I

DEBUG flwr 2023-07-06 14:45:53,534 | server.py:179 | evaluate_round 10 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:53,535 | server.py:215 | fit_round 11: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 288/384 [=====================>........] - ETA: 0s - loss: 0.5082 - accuracy: 0.7160
(launch_and_evaluate pid=36636) 336/384 [=========================>....] - ETA: 0s - loss: 0.5106 - accuracy: 0.7148
(launch_and_evaluate pid=32936) 
(launch_and_evaluate pid=32936) 284/384 [=====================>........] - ETA: 0s - loss: 0.5101 - accuracy: 0.7193
(launch_and_evaluate pid=32936) 331/384 [========================>.....] - ETA: 0s - loss: 0.5073 - accuracy: 0.7214
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 291/384 [=====================>........] - ETA: 0s - loss: 0.5055 - accuracy: 0.7197
(launch_and_evaluate pid=49088) 338/384 [=========================>....] - ETA: 0s - loss: 0.5035 - accuracy: 0.7205
(launch_and_evaluate pid=54092) 
(launch_and_evaluate pid=54092) 289/384 [=====================>........] - ETA: 0s - loss: 0.5201 - accuracy: 0.7180
(launch_and_evaluate pid=54092) 337/384 [========

DEBUG flwr 2023-07-06 14:45:56,159 | server.py:229 | fit_round 11 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 2s 3ms/step - loss: 0.5175 - accuracy: 0.7316
(launch_and_fit pid=36636) Client  7 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 2s 3ms/step - loss: 0.5208 - accuracy: 0.7153
(launch_and_fit pid=54948) Client  0 Training complete...
Server Evaluating... 11
958/958 [==============================] - 1s 885us/step


INFO flwr 2023-07-06 14:45:58,310 | server.py:116 | fit progress: (11, 0.5047951340675354, {'accuracy': 0.7283080220222473}, 57.24205680000159)
DEBUG flwr 2023-07-06 14:45:58,311 | server.py:165 | evaluate_round 11: strategy sampled 5 clients (out of 10)


Prediction:  [[2.11715978e-05 1.49446782e-02 1.62413456e-02 ... 9.79623258e-01
  5.29660378e-03 3.65638398e-02]
 [9.99928832e-01 9.03233588e-02 1.74807888e-02 ... 3.52788344e-02
  2.99549196e-02 1.21108375e-01]
 [9.99998629e-01 8.78369153e-01 2.62109283e-02 ... 9.98003967e-03
  1.07191831e-01 8.95311683e-02]
 ...
 [9.99950528e-01 4.81464528e-02 2.90885493e-02 ... 1.47523386e-02
  3.21654230e-02 1.54988453e-01]
 [4.17524949e-03 9.93478000e-01 4.34693834e-03 ... 2.46207379e-02
  4.99824435e-03 1.12506177e-03]
 [8.84782366e-06 1.43431639e-02 1.52224954e-02 ... 9.82205093e-01
  3.47496266e-03 2.16275565e-02]] (30645, 15)
Server Evaluating complete... 0.7283080220222473 0.5047951340675354
(launch_and_evaluate pid=36636) Client ID: 4
(launch_and_evaluate pid=54948) Client ID: 7
(launch_and_evaluate pid=49088) Client ID: 1
(launch_and_evaluate pid=36612) Client ID: 9
(launch_and_evaluate pid=54092) Client ID: 6
(launch_and_evaluate pid=36636) Client  4 Evaluating...
(launch_and_evaluate pid=5

DEBUG flwr 2023-07-06 14:45:59,134 | server.py:179 | evaluate_round 11 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:45:59,135 | server.py:215 | fit_round 12: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 218/384 [================>.............] - ETA: 0s - loss: 0.5073 - accuracy: 0.7225
(launch_and_evaluate pid=36636) 261/384 [===================>..........] - ETA: 0s - loss: 0.5055 - accuracy: 0.7241
(launch_and_evaluate pid=36636) 309/384 [=======================>......] - ETA: 0s - loss: 0.5035 - accuracy: 0.7253
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 218/384 [================>.............] - ETA: 0s - loss: 0.5069 - accuracy: 0.7285
(launch_and_evaluate pid=54948) 263/384 [===================>..........] - ETA: 0s - loss: 0.5024 - accuracy: 0.7347
(launch_and_evaluate pid=54948) 310/384 [=======================>......] - ETA: 0s - loss: 0.5063 - accuracy: 0.7301
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 215/384 [===============>..............] - ETA: 0s - loss: 0.5108 - accuracy: 0.7240
(launch_and_evaluate pid=49088) 260/384 [===================>..........] - ETA: 0s

DEBUG flwr 2023-07-06 14:46:01,318 | server.py:229 | fit_round 12 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 322/384 [========================>.....] - ETA: 0s - loss: 0.5233 - accuracy: 0.7227
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 345/384 [=========================>....] - ETA: 0s - loss: 0.5106 - accuracy: 0.7250
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 344/384 [=========================>....] - ETA: 0s - loss: 0.5159 - accuracy: 0.7369
(launch_and_fit pid=32936) 
(launch_and_fit pid=32936) 362/384 [===========================>..] - ETA: 0s - loss: 0.5076 - accuracy: 0.7390
(launch_and_fit pid=26420) 
(launch_and_fit pid=26420) 370/384 [===========================>..] - ETA: 0s - loss: 0.5196 - accuracy: 0.7212
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 342/384 [=========================>....] - ETA: 0s - loss: 0.5116 - accuracy: 0.7297
(launch_and_fit pid=38564) 
(launch_and_fit pid=38564) 348/384 [==========================>...] - ETA: 0s - loss: 0.5256 - accuracy: 0.7267
(launch_and_fit pid=

INFO flwr 2023-07-06 14:46:03,430 | server.py:116 | fit progress: (12, 0.5007237792015076, {'accuracy': 0.7257953882217407}, 62.36212069999965)
DEBUG flwr 2023-07-06 14:46:03,431 | server.py:165 | evaluate_round 12: strategy sampled 5 clients (out of 10)


Prediction:  [[1.62755805e-05 1.40661262e-02 1.48608843e-02 ... 9.81850266e-01
  3.71144339e-03 2.88002621e-02]
 [9.99943376e-01 1.21823832e-01 1.56393182e-02 ... 4.67755012e-02
  2.67797001e-02 8.44719335e-02]
 [9.99999106e-01 9.17214572e-01 2.83438172e-02 ... 1.11807035e-02
  1.24325365e-01 7.05614686e-02]
 ...
 [9.99961257e-01 6.75609857e-02 2.86578517e-02 ... 1.87354162e-02
  2.97215525e-02 1.14240296e-01]
 [4.38914075e-03 9.94131982e-01 4.00995044e-03 ... 3.22448611e-02
  3.92478053e-03 8.16102896e-04]
 [6.37743051e-06 1.34174265e-02 1.43469526e-02 ... 9.84425247e-01
  2.38632597e-03 1.66745372e-02]] (30645, 15)
Server Evaluating complete... 0.7257953882217407 0.5007237792015076
(launch_and_evaluate pid=36636) Client ID: 3
(launch_and_evaluate pid=36636) Client  3 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 9
(launch_and_evaluate pid=54948) Client  9 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 7
(launch_and_evaluate pid=49088) Client  7 Evaluating...
(lau

DEBUG flwr 2023-07-06 14:46:04,439 | server.py:179 | evaluate_round 12 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:46:04,440 | server.py:215 | fit_round 13: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 297/384 [======================>.......] - ETA: 0s - loss: 0.5026 - accuracy: 0.7197
(launch_and_evaluate pid=36636) 344/384 [=========================>....] - ETA: 0s - loss: 0.5004 - accuracy: 0.7230
(launch_and_evaluate pid=36636) 384/384 [==============================] - 1s 1ms/step - loss: 0.4979 - accuracy: 0.7236
(launch_and_evaluate pid=36636) Client  3 Evaluating complete... 0.7236090898513794 0.49788182973861694
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 299/384 [======================>.......] - ETA: 0s - loss: 0.4892 - accuracy: 0.7349
(launch_and_evaluate pid=54948) 347/384 [==========================>...] - ETA: 0s - loss: 0.4901 - accuracy: 0.7351
(launch_and_evaluate pid=54948) 384/384 [==============================] - 1s 1ms/step - loss: 0.4925 - accuracy: 0.7340
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 298/384 [======================>.......] - ETA: 0s - lo

DEBUG flwr 2023-07-06 14:46:06,203 | server.py:229 | fit_round 13 received 10 results and 0 failures


(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 356/384 [==========================>...] - ETA: 0s - loss: 0.5036 - accuracy: 0.7365
(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 384/384 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7328
(launch_and_fit pid=36820) Client  7 Training complete...
(launch_and_fit pid=32936) 
(launch_and_fit pid=32936) 381/384 [============================>.] - ETA: 0s - loss: 0.5136 - accuracy: 0.7241
(launch_and_fit pid=32936) 384/384 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7247
(launch_and_fit pid=32936) Client  0 Training complete...
(launch_and_fit pid=49088) Client  8 Training complete...
(launch_and_fit pid=36612) 
(launch_and_fit pid=36612) 384/384 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7293
(launch_and_fit pid=36612) Client  4 Training complete...
(launch_and_fit pid=54092) 
(launch_and_fit pid=54092) 360/384 [====================

INFO flwr 2023-07-06 14:46:08,293 | server.py:116 | fit progress: (13, 0.4973461627960205, {'accuracy': 0.7258280515670776}, 67.22533979999935)
DEBUG flwr 2023-07-06 14:46:08,294 | server.py:165 | evaluate_round 13: strategy sampled 5 clients (out of 10)


Prediction:  [[1.4278598e-05 1.0909916e-02 1.1994195e-02 ... 9.8115593e-01
  3.1058164e-03 3.0049298e-02]
 [9.9994808e-01 1.2049390e-01 1.2605176e-02 ... 4.4032376e-02
  2.8824691e-02 8.9813061e-02]
 [9.9999923e-01 9.3261951e-01 2.3635905e-02 ... 9.2239697e-03
  1.6392031e-01 6.7448147e-02]
 ...
 [9.9996632e-01 7.0835263e-02 2.4036169e-02 ... 1.7155252e-02
  3.1801492e-02 1.1817759e-01]
 [4.9858782e-03 9.9380744e-01 2.5169884e-03 ... 2.9825302e-02
  3.5909896e-03 7.0499192e-04]
 [5.1222901e-06 1.0367306e-02 1.1473214e-02 ... 9.8368883e-01
  1.9811778e-03 1.7329294e-02]] (30645, 15)
Server Evaluating complete... 0.7258280515670776 0.4973461627960205
(launch_and_evaluate pid=36636) Client ID: 8
(launch_and_evaluate pid=36636) Client  8 Evaluating...
(launch_and_evaluate pid=36820) Client ID: 7
(launch_and_evaluate pid=36820) Client  7 Evaluating...
(launch_and_evaluate pid=32936) Client ID: 0
(launch_and_evaluate pid=32936) Client  0 Evaluating...
(launch_and_evaluate pid=36612) Client I

DEBUG flwr 2023-07-06 14:46:09,055 | server.py:179 | evaluate_round 13 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:46:09,056 | server.py:215 | fit_round 14: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 273/384 [====================>.........] - ETA: 0s - loss: 0.5108 - accuracy: 0.7182
(launch_and_evaluate pid=36636) 315/384 [=======================>......] - ETA: 0s - loss: 0.5091 - accuracy: 0.7224
(launch_and_evaluate pid=36636) 362/384 [===========================>..] - ETA: 0s - loss: 0.5070 - accuracy: 0.7236
(launch_and_evaluate pid=36820) 
(launch_and_evaluate pid=36820) 276/384 [====================>.........] - ETA: 0s - loss: 0.4975 - accuracy: 0.7318
(launch_and_evaluate pid=36820) 319/384 [=======================>......] - ETA: 0s - loss: 0.4994 - accuracy: 0.7278
(launch_and_evaluate pid=36820) 368/384 [===========================>..] - ETA: 0s - loss: 0.4974 - accuracy: 0.7277
(launch_and_evaluate pid=32936) 
(launch_and_evaluate pid=32936) 270/384 [====================>.........] - ETA: 0s - loss: 0.5003 - accuracy: 0.7183
(launch_and_evaluate pid=32936) 313/384 [=======================>......] - ETA: 0s

DEBUG flwr 2023-07-06 14:46:11,196 | server.py:229 | fit_round 14 received 10 results and 0 failures


(launch_and_fit pid=54948) Client  7 Training complete...
(launch_and_fit pid=49088) 
(launch_and_fit pid=49088) 384/384 [==============================] - 2s 2ms/step - loss: 0.5047 - accuracy: 0.7349
(launch_and_fit pid=49088) Client  4 Training complete...
Server Evaluating... 14
958/958 [==============================] - 1s 898us/step


INFO flwr 2023-07-06 14:46:13,387 | server.py:116 | fit progress: (14, 0.4943390190601349, {'accuracy': 0.724163830280304}, 72.32026160000169)
DEBUG flwr 2023-07-06 14:46:13,388 | server.py:165 | evaluate_round 14: strategy sampled 5 clients (out of 10)


Prediction:  [[1.1282599e-05 9.2929378e-03 1.0956719e-02 ... 9.7916067e-01
  2.7270487e-03 2.6292194e-02]
 [9.9993557e-01 1.4714426e-01 9.5150629e-03 ... 3.2379892e-02
  2.6307743e-02 5.9386201e-02]
 [9.9999899e-01 9.4781464e-01 2.3633357e-02 ... 7.4370159e-03
  1.9220816e-01 4.7786999e-02]
 ...
 [9.9995553e-01 9.5407784e-02 1.9535206e-02 ... 1.2480035e-02
  2.9616777e-02 8.0334783e-02]
 [4.0489328e-03 9.9314094e-01 1.5486091e-03 ... 2.5840759e-02
  2.6358101e-03 4.7132216e-04]
 [3.8115043e-06 8.8111600e-03 1.0501323e-02 ... 9.8149288e-01
  1.7156400e-03 1.5156886e-02]] (30645, 15)
Server Evaluating complete... 0.724163830280304 0.4943390190601349
(launch_and_evaluate pid=54948) Client ID: 8
(launch_and_evaluate pid=54948) Client  8 Evaluating...
(launch_and_evaluate pid=49088) Client ID: 1
(launch_and_evaluate pid=49088) Client  1 Evaluating...
(launch_and_evaluate pid=54092) Client ID: 6
(launch_and_evaluate pid=54092) Client  6 Evaluating...
(launch_and_evaluate pid=38564) Client ID

DEBUG flwr 2023-07-06 14:46:14,160 | server.py:179 | evaluate_round 14 received 5 results and 0 failures
DEBUG flwr 2023-07-06 14:46:14,161 | server.py:215 | fit_round 15: strategy sampled 10 clients (out of 10)


(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 313/384 [=======================>......] - ETA: 0s - loss: 0.5045 - accuracy: 0.7235
(launch_and_evaluate pid=54948) 357/384 [==========================>...] - ETA: 0s - loss: 0.5025 - accuracy: 0.7243
(launch_and_evaluate pid=54948) 384/384 [==============================] - 1s 1ms/step - loss: 0.5018 - accuracy: 0.7240
(launch_and_evaluate pid=54948) Client  8 Evaluating complete... 0.7240169644355774 0.5017784237861633
(launch_and_evaluate pid=49088) 
(launch_and_evaluate pid=49088) 316/384 [=======================>......] - ETA: 0s - loss: 0.4925 - accuracy: 0.7276
(launch_and_evaluate pid=49088) 361/384 [===========================>..] - ETA: 0s - loss: 0.4913 - accuracy: 0.7280
(launch_and_evaluate pid=49088) 384/384 [==============================] - 1s 1ms/step - loss: 0.4915 - accuracy: 0.7282
(launch_and_evaluate pid=49088) Client  1 Evaluating complete... 0.7281774878501892 0.4914689362049103
(launch_and_evalua

DEBUG flwr 2023-07-06 14:46:15,960 | server.py:229 | fit_round 15 received 10 results and 0 failures


(launch_and_fit pid=36820) 
(launch_and_fit pid=36820) 384/384 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7334
(launch_and_fit pid=36820) Client  3 Training complete...
(launch_and_fit pid=32936) 
(launch_and_fit pid=32936) 384/384 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7385
(launch_and_fit pid=32936) Client  4 Training complete...
(launch_and_fit pid=49088) Client  9 Training complete...
(launch_and_fit pid=54948) 
(launch_and_fit pid=54948) 384/384 [==============================] - 2s 2ms/step - loss: 0.4987 - accuracy: 0.7371
(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 376/384 [============================>.] - ETA: 0s - loss: 0.5086 - accuracy: 0.7338
(launch_and_fit pid=54948) Client  5 Training complete...
(launch_and_fit pid=36636) 
(launch_and_fit pid=36636) 384/384 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7332
(launch_and_fit pid=36636) Client  2 Training comple

INFO flwr 2023-07-06 14:46:18,093 | server.py:116 | fit progress: (15, 0.48875847458839417, {'accuracy': 0.7272312045097351}, 77.0248253000027)
DEBUG flwr 2023-07-06 14:46:18,094 | server.py:165 | evaluate_round 15: strategy sampled 5 clients (out of 10)


Prediction:  [[1.00377774e-05 7.52234180e-03 9.54464264e-03 ... 9.81108665e-01
  2.16920860e-03 2.24496946e-02]
 [9.99978185e-01 1.30046859e-01 1.02959806e-02 ... 3.09490915e-02
  3.12609076e-02 5.14558852e-02]
 [9.99999285e-01 9.52463269e-01 2.02520285e-02 ... 6.63362443e-03
  2.39020526e-01 3.38072106e-02]
 ...
 [9.99981225e-01 8.84933323e-02 2.22065710e-02 ... 1.28306635e-02
  3.57275121e-02 7.06765279e-02]
 [6.10289024e-03 9.92531359e-01 1.56141981e-03 ... 2.90506426e-02
  2.78450595e-03 4.16351773e-04]
 [3.26098484e-06 7.15603027e-03 9.48043726e-03 ... 9.83547270e-01
  1.34326541e-03 1.28031215e-02]] (30645, 15)
Server Evaluating complete... 0.7272312045097351 0.48875847458839417
(launch_and_evaluate pid=36636) Client ID: 9
(launch_and_evaluate pid=36636) Client  9 Evaluating...
(launch_and_evaluate pid=54948) Client ID: 5
(launch_and_evaluate pid=54948) Client  5 Evaluating...
(launch_and_evaluate pid=36820) Client ID: 0
(launch_and_evaluate pid=32936) Client ID: 4
(launch_and_ev

DEBUG flwr 2023-07-06 14:46:18,885 | server.py:179 | evaluate_round 15 received 5 results and 0 failures
INFO flwr 2023-07-06 14:46:18,885 | server.py:144 | FL finished in 77.81751050000094
INFO flwr 2023-07-06 14:46:18,886 | app.py:202 | app_fit: losses_distributed [(1, 0.6574431777000427), (2, 0.5727954506874084), (3, 0.5501438617706299), (4, 0.5382179856300354), (5, 0.5279483079910279), (6, 0.5175276160240173), (7, 0.5162710189819336), (8, 0.5135294795036316), (9, 0.5107775568962097), (10, 0.507382595539093), (11, 0.5027800619602203), (12, 0.4984209716320038), (13, 0.49956215023994444), (14, 0.4959253132343292), (15, 0.4854345083236694)]
INFO flwr 2023-07-06 14:46:18,887 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-07-06 14:46:18,887 | app.py:204 | app_fit: losses_centralized [(0, 3.021543502807617), (1, 0.659288763999939), (2, 0.5745646357536316), (3, 0.550567626953125), (4, 0.5368147492408752), (5, 0.5273430347442627), (6, 0.5202458500862122), (7, 0.51579636335372

(launch_and_evaluate pid=36636) 
(launch_and_evaluate pid=36636) 255/384 [==================>...........] - ETA: 0s - loss: 0.4781 - accuracy: 0.7306
(launch_and_evaluate pid=36636) 300/384 [======================>.......] - ETA: 0s - loss: 0.4776 - accuracy: 0.7317
(launch_and_evaluate pid=36636) 349/384 [==========================>...] - ETA: 0s - loss: 0.4785 - accuracy: 0.7326
(launch_and_evaluate pid=54948) 
(launch_and_evaluate pid=54948) 258/384 [===================>..........] - ETA: 0s - loss: 0.4861 - accuracy: 0.7307
(launch_and_evaluate pid=54948) 302/384 [======================>.......] - ETA: 0s - loss: 0.4835 - accuracy: 0.7311
(launch_and_evaluate pid=54948) 351/384 [==========================>...] - ETA: 0s - loss: 0.4840 - accuracy: 0.7295
(launch_and_evaluate pid=36820) 
(launch_and_evaluate pid=36820) 260/384 [===================>..........] - ETA: 0s - loss: 0.4921 - accuracy: 0.7165
(launch_and_evaluate pid=36820) 307/384 [======================>.......] - ETA: 0s

History (loss, distributed):
	round 1: 0.6574431777000427
	round 2: 0.5727954506874084
	round 3: 0.5501438617706299
	round 4: 0.5382179856300354
	round 5: 0.5279483079910279
	round 6: 0.5175276160240173
	round 7: 0.5162710189819336
	round 8: 0.5135294795036316
	round 9: 0.5107775568962097
	round 10: 0.507382595539093
	round 11: 0.5027800619602203
	round 12: 0.4984209716320038
	round 13: 0.49956215023994444
	round 14: 0.4959253132343292
	round 15: 0.4854345083236694
History (loss, centralized):
	round 0: 3.021543502807617
	round 1: 0.659288763999939
	round 2: 0.5745646357536316
	round 3: 0.550567626953125
	round 4: 0.5368147492408752
	round 5: 0.5273430347442627
	round 6: 0.5202458500862122
	round 7: 0.5157963633537292
	round 8: 0.5118222236633301
	round 9: 0.5099111795425415
	round 10: 0.5064926147460938
	round 11: 0.5047951340675354
	round 12: 0.5007237792015076
	round 13: 0.4973461627960205
	round 14: 0.4943390190601349
	round 15: 0.48875847458839417
History (metrics, centralized):
{