In [1]:
import pandas as pd

import numpy as np

df = pd.read_csv("../datasets/Edge-IIoT/Edge-IIoTset dataset/Selected dataset for ML and DL/DNN-EdgeIIoT-dataset.csv", low_memory=False) 

In [2]:
df.head(5)

print(df['Attack_type'].value_counts())

Normal                   1615643
DDoS_UDP                  121568
DDoS_ICMP                 116436
SQL_injection              51203
Password                   50153
Vulnerability_scanner      50110
DDoS_TCP                   50062
DDoS_HTTP                  49911
Uploading                  37634
Backdoor                   24862
Port_Scanning              22564
XSS                        15915
Ransomware                 10925
MITM                        1214
Fingerprinting              1001
Name: Attack_type, dtype: int64


In [3]:
from sklearn.utils import shuffle

drop_columns = ["frame.time", "arp.src.proto_ipv4","arp.dst.proto_ipv4", 

         "http.file_data","http.request.full_uri","icmp.transmit_timestamp",

         "http.request.uri.query", "tcp.options","tcp.payload","tcp.srcport",

         "tcp.dstport", "udp.port", "mqtt.msg"]

# "ip.src_host", "ip.dst_host", 

df.drop(drop_columns, axis=1, inplace=True)

df.dropna(axis=0, how='any', inplace=True)

df.drop_duplicates(subset=None, keep="first", inplace=True)

df = shuffle(df)

df.isna().sum()

print(df['Attack_type'].value_counts())

Normal                   1364002
DDoS_UDP                  121567
DDoS_ICMP                 116431
SQL_injection              50829
DDoS_TCP                   50062
Vulnerability_scanner      50029
Password                   49936
DDoS_HTTP                  48544
Uploading                  36956
Backdoor                   24029
Port_Scanning              19979
XSS                        15069
Ransomware                  9692
Fingerprinting               857
MITM                         364
Name: Attack_type, dtype: int64


In [4]:
df

ip.src_host    ip.dst_host  arp.opcode  arp.hw.size  icmp.checksum  \
1056004  192.168.0.128  192.168.0.101         0.0          0.0            0.0   
978518   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
763717   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
878638   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
1906549  192.168.0.170  192.168.0.128         0.0          0.0            0.0   
...                ...            ...         ...          ...            ...   
2198741  172.12.115.99  192.168.0.128         0.0          0.0          700.0   
111749   192.168.0.101  192.168.0.128         0.0          0.0            0.0   
1936250  192.168.0.128  192.168.0.170         0.0          0.0            0.0   
1127633  192.168.0.101  192.168.0.128         0.0          0.0            0.0   
600554               0              0         0.0          0.0            0.0   

         icmp.seq_le  icmp.unused  http.content_length http.request.method  \
1056004          0.0          0.0                  0.0                 0.0   
978518           0.0          0.0                  0.0                 0.0   
763717           0.0          0.0                  0.0                 0.0   
878638           0.0          0.0                  0.0                 0.0   
1906549          0.0          0.0                 57.0                 GET   
...              ...          ...                  ...                 ...   
2198741      15534.0          0.0                  0.0                 0.0   
111749           0.0          0.0                  0.0                 0.0   
1936250          0.0          0.0                277.0                   0   
1127633          0.0          0.0                  0.0                 0.0   
600554           0.0          0.0                  0.0                 0.0   

        http.referer  ... mqtt.proto_len  mqtt.protoname  mqtt.topic  \
1056004          0.0  ...            0.0               0           0   
978518           0.0  ...            0.0               0           0   
763717           0.0  ...            0.0               0           0   
878638           0.0  ...            0.0               0           0   
1906549            0  ...            0.0             0.0         0.0   
...              ...  ...            ...             ...         ...   
2198741          0.0  ...            0.0             0.0         0.0   
111749           0.0  ...            0.0               0           0   
1936250            0  ...            0.0             0.0         0.0   
1127633          0.0  ...            0.0               0           0   
600554           0.0  ...            0.0               0           0   

         mqtt.topic_len  mqtt.ver  mbtcp.len  mbtcp.trans_id  mbtcp.unit_id  \
1056004             0.0       0.0        0.0             0.0            0.0   
978518              0.0       0.0        0.0             0.0            0.0   
763717              0.0       0.0        0.0             0.0            0.0   
878638              0.0       0.0        0.0             0.0            0.0   
1906549             0.0       0.0        0.0             0.0            0.0   
...                 ...       ...        ...             ...            ...   
2198741             0.0       0.0        0.0             0.0            0.0   
111749              0.0       0.0        0.0             0.0            0.0   
1936250             0.0       0.0        0.0             0.0            0.0   
1127633             0.0       0.0        0.0             0.0            0.0   
600554              0.0       0.0        0.0             0.0            0.0   

         Attack_label            Attack_type  
1056004             0                 Normal  
978518              0                 Normal  
763717              0                 Normal  
878638              0                 Normal  
1906549             1  Vulnerability_scanner  
...  

In [5]:
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing

def encode_text_dummy(df, name):

    dummies = pd.get_dummies(df[name])

    for x in dummies.columns:

        dummy_name = f"{name}-{x}"

        df[dummy_name] = dummies[x]

    df.drop(name, axis=1, inplace=True)

encode_text_dummy(df,'http.request.method')

encode_text_dummy(df,'http.referer')

encode_text_dummy(df,"http.request.version")

encode_text_dummy(df,"dns.qry.name.len")

encode_text_dummy(df,"mqtt.conack.flags")

encode_text_dummy(df,"mqtt.protoname")

encode_text_dummy(df,"mqtt.topic")

In [6]:
df

ip.src_host    ip.dst_host  arp.opcode  arp.hw.size  icmp.checksum  \
1056004  192.168.0.128  192.168.0.101         0.0          0.0            0.0   
978518   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
763717   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
878638   192.168.0.128  192.168.0.101         0.0          0.0            0.0   
1906549  192.168.0.170  192.168.0.128         0.0          0.0            0.0   
...                ...            ...         ...          ...            ...   
2198741  172.12.115.99  192.168.0.128         0.0          0.0          700.0   
111749   192.168.0.101  192.168.0.128         0.0          0.0            0.0   
1936250  192.168.0.128  192.168.0.170         0.0          0.0            0.0   
1127633  192.168.0.101  192.168.0.128         0.0          0.0            0.0   
600554               0              0         0.0          0.0            0.0   

         icmp.seq_le  icmp.unused  http.content_length  http.response  \
1056004          0.0          0.0                  0.0            0.0   
978518           0.0          0.0                  0.0            0.0   
763717           0.0          0.0                  0.0            0.0   
878638           0.0          0.0                  0.0            0.0   
1906549          0.0          0.0                 57.0            0.0   
...              ...          ...                  ...            ...   
2198741      15534.0          0.0                  0.0            0.0   
111749           0.0          0.0                  0.0            0.0   
1936250          0.0          0.0                277.0            1.0   
1127633          0.0          0.0                  0.0            0.0   
600554           0.0          0.0                  0.0            0.0   

         http.tls_port  ...  mqtt.conack.flags-1471198  \
1056004            0.0  ...                          0   
978518             0.0  ...                          0   
763717             0.0  ...                          0   
878638             0.0  ...                          0   
1906549            0.0  ...                          0   
...                ...  ...                        ...   
2198741            0.0  ...                          0   
111749             0.0  ...                          0   
1936250            0.0  ...                          0   
1127633            0.0  ...                          0   
600554             0.0  ...                          0   

         mqtt.conack.flags-1471199  mqtt.conack.flags-1574358  \
1056004                          0                          0   
978518                           0                          0   
763717                           0                          0   
878638                           0                          0   
1906549                          0                          0   
...                            ...                        ...   
2198741                          0                          0   
111749                           0                          0   
1936250                          0                          0   
1127633                          0                          0   
600554                           0                          0   

         mqtt.conack.flags-1574359  mqtt.protoname-0  mqtt.protoname-0.0  \
1056004                          0                 1                   0   
978518                           0                 1                   0   
763717                           0                 1                   0   
878638                           0                 1                   0   
1906549                          0                 0                   1   
...                            ...               ...                 ...   
2198741                          0                 0                   1   
111749                           0                 1                   0   

In [7]:
df.to_csv('preprocessed_DNN_PL.csv', encoding='utf-8')

In [8]:
internal_ip = df[ df['ip.dst_host'].str.startswith('192.168') ]['ip.dst_host'].unique()

In [9]:
for i in range(len(internal_ip)):
    print ("--- ADDRESS ---")
    print ("Address:", internal_ip[i])
    print ("--- Src IP ---")
    print (df[df['ip.src_host'] == internal_ip[i] ]['Attack_type'].value_counts())
    print ("--- Dst IP ---")
    print (df[ df['ip.dst_host'] == internal_ip[i] ]['Attack_type'].value_counts())

--- ADDRESS ---
Address: 192.168.0.101
--- Src IP ---
Normal    548715
MITM           1
Name: Attack_type, dtype: int64
--- Dst IP ---
Normal        544743
Backdoor           2
Ransomware         1
Name: Attack_type, dtype: int64
--- ADDRESS ---
Address: 192.168.0.128
--- Src IP ---
Normal                   546064
DDoS_UDP                 110034
Password                  25263
Vulnerability_scanner     25121
SQL_injection             24695
DDoS_TCP                  20910
DDoS_ICMP                 19949
Uploading                 16809
DDoS_HTTP                 16568
Backdoor                  12199
Port_Scanning              9988
XSS                        7105
Ransomware                 4894
Fingerprinting              386
MITM                          1
Name: Attack_type, dtype: int64
--- Dst IP ---
Normal                   549478
DDoS_ICMP                 96479
DDoS_HTTP                 31973
DDoS_TCP                  29151
SQL_injection             26130
Vulnerability_scanner     249

In [10]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

data_mod = df
label = data_mod['Attack_type']
le = preprocessing.LabelEncoder()
label_n = le.fit_transform(label.values)

X_train_df, X_test_df, y_train_df, y_test_df = train_test_split(data_mod, label_n, stratify=label_n, test_size=0.2, random_state=42)
data_mod = data_mod.drop(['ip.src_host', 'ip.dst_host', 'Attack_type',  'Attack_label'], axis=1)

# Scaling of features to fit within defined range
scaled_features = StandardScaler().fit_transform(data_mod.values)
X_train, X_test, y_train, y_test = train_test_split(scaled_features, label_n, stratify=label_n, test_size=0.2, random_state=42)


In [11]:
from sklearn.model_selection import StratifiedKFold

NUM_OF_STRATIFIED_CLIENTS = 5

fl_X_train = []
fl_y_train = []

skf = StratifiedKFold(n_splits=NUM_OF_STRATIFIED_CLIENTS, shuffle=True, random_state=42)
print (skf.get_n_splits(X_train, y_train))

for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    print (train_index)
    print (test_index)
    fl_X_train.append(X_train[train_index])
    fl_y_train.append(y_train[test_index]) 

5
[      0       1       2 ... 1566670 1566673 1566675]
[      4       6       8 ... 1566671 1566672 1566674]
[      2       4       6 ... 1566673 1566674 1566675]
[      0       1       3 ... 1566652 1566655 1566665]
[      0       1       2 ... 1566672 1566673 1566674]
[      7      10      12 ... 1566668 1566669 1566675]
[      0       1       3 ... 1566673 1566674 1566675]
[      2      11      21 ... 1566656 1566660 1566662]
[      0       1       2 ... 1566672 1566674 1566675]
[     14      18      20 ... 1566667 1566670 1566673]


In [12]:
for i in range(len(fl_X_train)):
    print (i, fl_X_train[i].shape)
    #print (list(fl_X_train[i][0]))

0 (1253340, 95)
1 (1253341, 95)
2 (1253341, 95)
3 (1253341, 95)
4 (1253341, 95)


In [13]:
# CHECK IF THIS REMAINS THE SAME OR CHANGED
NUM_OF_CLIENTS = len(fl_X_train)
print ("NUM_OF_CLIENTS:", NUM_OF_CLIENTS)

NUM_OF_ROUNDS = 3

print ("Checking data split groups")
for i in range(len(fl_X_train)):
    print (i, ':', "X shape", fl_X_train[i].shape, " Y shape:" , fl_y_train[i].shape)

print ("Importing Federated Learning environment...")
import flwr as fl
import numpy as np
import tensorflow as tf
import os
print("flwr", fl.__version__)
print("numpy", np.__version__)
print("tf", tf.__version__)
# Make TensorFlow log less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation

class NumpyFlowerClient(fl.client.NumPyClient):
    def __init__(self, cid, model, train_data, train_labels):
        self.model = model
        self.cid = cid
        self.train_data = train_data
        self.train_labels = train_labels

    def get_parameters(self, config):
        return self.model.get_weights()

    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Training...")
        self.model.fit(self.train_data, self.train_labels, epochs=1, batch_size=32)
        print ("Client ", self.cid, "Training complete...")
        return self.model.get_weights(), len(self.train_data), {}

    def evaluate(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Evaluating...")
        loss, accuracy = self.model.evaluate(self.train_data, self.train_labels, batch_size=32)
        print ("Client ", self.cid, "Evaluating complete...", accuracy, loss)
        return loss, len(self.train_data), {"accuracy": accuracy}


def client_fn(cid: str) -> NumpyFlowerClient:
    """Create a Flower client representing a single organization."""

    # Load model
    #model = tf.keras.applications.MobileNetV2((32, 32, 3), classes=10, weights=None)
    #model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

    print ("Client ID:", cid)

    model = Sequential([
      #Flatten(input_shape=(79,1)),
      Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
      Dense(256, activation='sigmoid'),
      Dense(128, activation='sigmoid'), 
      #Dense(18, activation='sigmoid'),  
      Dense(len(label.unique()), activation='sigmoid')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    partition_id = int(cid)
    X_train_c = fl_X_train[partition_id]
    y_train_c = fl_y_train[partition_id]

    # Create a  single Flower client representing a single organization
    return NumpyFlowerClient(cid, model, X_train_c, y_train_c)


print ("Deploy simulation...")


def get_evaluate_fn(server_model):
    """Return an evaluation function for server-side evaluation."""
    # The `evaluate` function will be called after every round
    def evaluate(server_round, parameters, config):
        # Update model with the latest parameters
        server_model.set_weights(parameters)
        print ("Server Evaluating...")
        loss, accuracy = server_model.evaluate(X_test, y_test)
        print ("Server Evaluating complete...", accuracy, loss)
        return loss, {"accuracy": accuracy}
    return evaluate



server_model = Sequential([
      #Flatten(input_shape=(79,1)),
      Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
      Dense(256, activation='sigmoid'),
      Dense(128, activation='sigmoid'), 
      #Dense(18, activation='sigmoid'),  
      Dense(len(label.unique()), activation='sigmoid')
    ])
server_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])




# Create FedAvg strategy
strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        fraction_evaluate=0.5,
        min_fit_clients=2, #10,
        min_evaluate_clients=2, #5,
        min_available_clients=2, #10,
        evaluate_fn=get_evaluate_fn(server_model),
        #evaluate_metrics_aggregation_fn=weighted_average,
)

# Start simulation
fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=NUM_OF_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=NUM_OF_ROUNDS),
    strategy=strategy,
)

NUM_OF_CLIENTS: 5
Checking data split groups
0 : X shape (1253340, 95)  Y shape: (313336,)
1 : X shape (1253341, 95)  Y shape: (313335,)
2 : X shape (1253341, 95)  Y shape: (313335,)
3 : X shape (1253341, 95)  Y shape: (313335,)
4 : X shape (1253341, 95)  Y shape: (313335,)
Importing Federated Learning environment...
flwr 1.3.0
numpy 1.24.2
tf 2.11.0
Deploy simulation...


INFO flwr 2023-07-02 16:03:41,622 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=3, round_timeout=None)
2023-07-02 16:03:48,179	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
INFO flwr 2023-07-02 16:03:52,608 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 24.0, 'node:127.0.0.1': 1.0, 'memory': 6599022183.0, 'GPU': 1.0, 'object_store_memory': 3299511091.0}
INFO flwr 2023-07-02 16:03:52,609 | server.py:86 | Initializing global parameters
INFO flwr 2023-07-02 16:03:52,610 | server.py:270 | Requesting initial parameters from one random client
INFO flwr 2023-07-02 16:04:02,562 | server.py:274 | Received initial parameters from one random client
INFO flwr 2023-07-02 16:04:02,562 | server.py:88 | Evaluating initial parameters


(launch_and_get_parameters pid=28452) Client ID: 4
Server Evaluating...
12240/12240 [==============================] - 12s 954us/step - loss: 3.1554 - accuracy: 0.0049


INFO flwr 2023-07-02 16:04:14,859 | server.py:91 | initial parameters (loss, other metrics): 3.155425548553467, {'accuracy': 0.004948042798787355}
INFO flwr 2023-07-02 16:04:14,860 | server.py:101 | FL starting
DEBUG flwr 2023-07-02 16:04:14,860 | server.py:215 | fit_round 1: strategy sampled 5 clients (out of 5)


Server Evaluating complete... 0.004948042798787355 3.155425548553467


(pid=) [2023-07-02 16:04:28,500 C 11196 26664] (raylet.exe) dlmalloc.cc:129:  Check failed: *handle != nullptr CreateFileMapping() failed. GetLastError() = 1450
(pid=) *** StackTrace Information ***
(pid=) 
2023-07-02 16:04:42,582	WARNING worker.py:1851 -- The node with node id: c0c75abf6d5a95d545cf6f5da921429b1782465856508470180bf7be and address: 127.0.0.1 and node name: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
